### ISSUE TITLE
Eval Vulnerability.

### ISSUE THREAD

**Issue by TheUntraceable** [MilkshakeTheCoder/Cafe_Bot#1]
**Eval Command Vulnerability.**
The eval command allows **anyone** to run code on YOUR PERSONAL MACHINE.

**To Reproduce**
1. Invoke the `eval` command.

**Expected behavior**
To be told only the owner can run this command or be able to run this command but the code will be ran in an external "server"
Just slap in a `@commands.is_owner()` and then you're safe.

**Comment by The007Programmer** [comment]
Yea thanks for the input, I fixed that!
