### ISSUE TITLE
how do I contribute?

### ISSUE THREAD

**Issue by notkirito** [MilkshakeTheCoder/Cafe_Bot#2]
Where could I contribute?

**Comment by MilkshakeTheCoder** [comment]
> Where could I contribute?

I really appreciate your eagerness to help @notkirito! Before you can contribute, I would like to get to know you better, and the best way to do that would be if you [Join our Discord Server!](https://discord.gg/CtNTUX4znA), then start a DM with me, so we can discuss this more in detail. Thanks

**Comment by MilkshakeTheCoder** [comment]
> Where could I contribute?

also, are you from The Coding Academy?

**Comment by notkirito** [comment]
Nope, I just self-learned Python and will learn discord.py soon

**Comment by MilkshakeTheCoder** [comment]
> Nope, I just self-learned Python and will learn discord.py soon
> […](#)
> Le 16 mai 2021 à 15:14, MilkshakeTheCoder ***@***.***> a écrit : ﻿ Where could I contribute? also, are you from The Coding Academy? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I'll keep you updated on when we are accepting more contributors, for now, I'm sorry to say that we cannot add you. Also, how did you find this Git Repo? Just wondering.

**Comment by notkirito** [comment]
Andrewthederp is my friend and i clicked "following", found you, then clicked this pinned repo.
